version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fiap_network

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm start
    networks:
      - fiap_network

volumes:
  postgres_data:

networks:
  fiap_network: