apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-lanches-api-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fiap-lanches-api-pod
  template:
    metadata:
      labels:
        app: fiap-lanches-api-pod
    spec:
      containers:
      - name: fiap-lanches-app
        image: fiaplanches165/fiap-lanches-app:1.0.13
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_HOST
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_DB
        ports:
        - containerPort: 3000