apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: fiap-lanches-postgres-db-instance
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_USER: postgres
  POSTGRES_HOST: fiap-lanches-postgres-db-instance.c3ayceu2o7gb.sa-east-1.rds.amazonaws.com
